### ISSUE TITLE
fix container title

### ISSUE THREAD

**Issue by Landers1037** [SC4D/SC4D.github.io#1]
# fix title when on mobile device
```css
@media (max-width: 600px) {
  compare-title.compare-title-sm {
    font-size: 0.85rem;
  }
}
```
